# Pick your baseUrl here:
@baseUrl = http://localhost:3002
# @baseUrl = https://api.lingcrawl.dev

### Summary
POST {{baseUrl}}/v2/scrape HTTP/1.1
Authorization: Bearer {{$dotenv TEST_API_KEY}}
content-type: application/json

{
  "url": "https://docs.lingcrawl.dev",
  "formats": ["summary"]
}

### JSON
POST {{baseUrl}}/v2/scrape HTTP/1.1
Authorization: Bearer {{$dotenv TEST_API_KEY}}
content-type: application/json

{
  "url": "https://docs.lingcrawl.dev",
  "formats": [{
    "type": "json",
    "schema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      }
    }
  }]
}

### Change Tracking
POST {{baseUrl}}/v2/scrape HTTP/1.1
Authorization: Bearer {{$dotenv TEST_API_KEY}}
content-type: application/json

{
  "url": "https://docs.lingcrawl.dev",
  "formats": [{
    "type": "changeTracking",
    "modes": ["git-diff"]
  }]
}

### Parsers
POST {{baseUrl}}/v2/scrape HTTP/1.1
Authorization: Bearer {{$dotenv TEST_API_KEY}}
content-type: application/json

{
  "url": "https://www.orimi.com/pdf-test.pdf",
  "parsers": {
    "pdf": false
  }
}
